### ISSUE TITLE
Два параметра для choose_plural вместо трех

### ISSUE THREAD

**Issue by l0kix2** [last-partizan/pytils#15]
Кажется существуют случаи, когда choose_plural может принимать 2 варианта в строке variants и интерпретировать, что множественное число для 2 и для 5 в данном падеже одинаковое.
Например 

``` python
choose_plural(1, 'проектом,проектами')
>>> 'проектом'
choose_plural(2, 'проектом,проектами')
>>> 'проектами'
choose_plural(5, 'проектом,проектами')
>>> 'проектами'
```

Если то, что я описал корректно, попробую сделать пуллреквест.

**Comment by y10h** [comment]
Закрываю за давностью.
