### ISSUE TITLE
Как отформатировать now с помощью pytils_dt?

### ISSUE THREAD

**Issue by softshape** [last-partizan/pytils#21]
Добрый день,

вот так работает - {% now "d" %}
вот так не работает - {% now|ru_strftime:"%d %B" %}

Вопрос: как прямо в шаблоне правильно скормить текущее время фильтру pytils?

**Comment by last-partizan** [comment]
Похоже только если передавать `now = timezone.now()` а потом `{{ now|ru_strftime }}`
