### ISSUE TITLE
Обновить версию в PyPI

### ISSUE THREAD

**Issue by emorozov** [last-partizan/pytils#42]
Добрый день!
Версия на PyPI уже серьезно устарела. Последние версии Python и Django сейчас 3.8 и 3.0 соответственно.

В https://github.com/last-partizan/pytils/pull/41 удалил весь код, относящийся к Python 2, добавил python 3.8 и Django 3.0 в тесты tox.

**Comment by last-partizan** [comment]
Как-то я пропустил это, смержил уже другой PR с такими же фиксами, и скоро выкатим новый релиз.
