### ISSUE TITLE
Поддержка Django 3

### ISSUE THREAD

**Issue by yamnikov-oleg** [last-partizan/pytils#45]
В [pyproject.toml](https://github.com/last-partizan/pytils/blob/d09ecdfca203aa67814487fb07792a000995b072/pyproject.toml#L9) версию Django зафиксировали на `^4.0.2`, но судя по тестам поддержка django 3 еще не брошена? 

pipenv не ставит pytils 4 вместе с django 3.2, ссылаясь на это ограничение.

**Comment by last-partizan** [comment]
Хм, а это интересно, я ожидал что в pyproject будет версия только для dev окружения.

Можешь поправить там минимальную версию, проверить, сделать мерж и я выкачу фикс.
